# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 358606b8fa9b393ebffa05c65bfd2c2db35a4cde2214643a5ae8636d51294c97d886d163a1ad1912f724716d50b91eb4d86bcbd6f9f3a54fcfba8ec03ae733b7

test:
  secret_key_base: fc8506e915cfe94cd0451b4a73b2af067f384022b661a76a015a59d4b1b4eee3369428e8ad170d9264f34c698f7bcac749b6ce60d66f88815887294dd0006d38

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
